//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infosys.Solutions.Superbot.Resource.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Environment_Scan_Metric_Details
    {
        public int Id { get; set; }
        public int EnvironmentScanMetricID { get; set; }
        public string MetricName { get; set; }
        public int MetricID { get; set; }
        public string MetricKey { get; set; }
        public string AttributeName { get; set; }
        public string AttributeValue { get; set; }
        public string DisplayName { get; set; }
        public bool isActive { get; set; }
        public int TenantID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Environment_Scan_Metric Environment_Scan_Metric { get; set; }
    }
}
