//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infosys.Solutions.Superbot.Resource.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Environment_Scan_Metric_Anomaly_Details
    {
        public int Id { get; set; }
        public string ResourceId { get; set; }
        public int ObservationId { get; set; }
        public int OldVersion { get; set; }
        public int NewVersion { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string MetricName { get; set; }
        public string MetricKey { get; set; }
        public int MetricId { get; set; }
        public string AttributeName { get; set; }
        public string AttributeValue { get; set; }
        public string AttributeStatus { get; set; }
        public string OldValue { get; set; }
        public int TenantId { get; set; }
        public int PlatformId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
