//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infosys.Solutions.Superbot.Resource.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class healthcheck_tracker
    {
        public int HealthCheckId { get; set; }
        public string ConfigId { get; set; }
        public string IncidentId { get; set; }
        public string Status { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Source { get; set; }
        public int TenantId { get; set; }
    
        public virtual healthcheck_master healthcheck_master { get; set; }
    }
}
