//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infosys.Solutions.Superbot.Resource.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class observation
    {
        public int observationid { get; set; }
        public string platformid { get; set; }
        public string resourceid { get; set; }
        public string resourcetypeid { get; set; }
        public string observableid { get; set; }
        public string observablename { get; set; }
        public string observation_status { get; set; }
        public Nullable<decimal> value { get; set; }
        public Nullable<System.DateTime> observationtime { get; set; }
        public string source_ip { get; set; }
        public string description { get; set; }
        public string event_type { get; set; }
        public string source { get; set; }
    }
}
