//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infosys.Solutions.Superbot.Resource.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class platform
    {
        public string platformid { get; set; }
        public string platformname { get; set; }
        public string executionmode { get; set; }
        public string runtimedetails { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string modifiedby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string host { get; set; }
    }
}
