//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infosys.Solutions.Superbot.Resource.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class resourcetype_metadata
    {
        public int ResourceTypeId { get; set; }
        public string AttributeName { get; set; }
        public string DefaultValue { get; set; }
        public string AttributeType { get; set; }
        public bool IsMandatory { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int TenantId { get; set; }
        public string Description { get; set; }
        public string DisplayName { get; set; }
        public Nullable<bool> issecret { get; set; }
    
        public virtual resourcetype resourcetype { get; set; }
    }
}
