//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infosys.Solutions.Superbot.Resource.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unhealthy_report_Remediation
    {
        public string ResourceId { get; set; }
        public string RemediationStatus { get; set; }
        public Nullable<System.DateTime> ObservationTime { get; set; }
        public int AnomalyId { get; set; }
    }
}
