// Copyright 2004, Microsoft Corporation
// Sample Code - Use restricted to terms of use defined in the accompanying license agreement (EULA.doc)

//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.4.1.0
// Schema file: CrMoPostCode.xsd
// Creation Date: 12/15/2006 9:53:53 AM
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace DataLoaderTest
{

    public struct Declarations2
    {
        public const string SchemaVersion = "";
    }



    //[Serializable]
    [XmlType(TypeName = "CrMoPostCode", Namespace = Declarations1.SchemaVersion), Serializable]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    public class CrMoPostCode1 //: Sse.Ngcsi.HostAccess.Common.Clauses.ClauseBase
    {

        [XmlElement(ElementName = "deliveryOfficeCode", IsNullable = false, Form = XmlSchemaForm.Qualified, DataType = "string", Namespace = Declarations1.SchemaVersion)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __deliveryOfficeCode;

        [XmlIgnore]
        public string deliveryOfficeCode
        {
            get { return __deliveryOfficeCode; }
            set { __deliveryOfficeCode = value; }
        }

        [XmlElement(ElementName = "mailingCategory", IsNullable = false, Form = XmlSchemaForm.Qualified, DataType = "string", Namespace = Declarations1.SchemaVersion)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __mailingCategory;

        [XmlIgnore]
        public string mailingCategory
        {
            get { return __mailingCategory; }
            set { __mailingCategory = value; }
        }

        [XmlElement(ElementName = "postCode", IsNullable = false, Form = XmlSchemaForm.Qualified, DataType = "string", Namespace = Declarations1.SchemaVersion)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __postCode;

        [XmlIgnore]
        public string postCode
        {
            get { return __postCode; }
            set { __postCode = value; }
        }

        public CrMoPostCode1()
            : base()
        {
        }
    }
}
