//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infosys.Solutions.Superbot.Infrastructure.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infosys.Solutions.Superbot.Infrastructure.Common.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawler Task Type cannot have multiple instances run ..
        /// </summary>
        public static string CrawlerMultipleInstanceError {
            get {
                return ResourceManager.GetString("CrawlerMultipleInstanceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! It seems like we are facing some technical difficulties at the moment, sorry for the inconvenience caused. Please try visiting us later; we are trying to resolve your issue..
        /// </summary>
        public static string Critical {
            get {
                return ResourceManager.GetString("Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data was not formatted correctly..
        /// </summary>
        public static string Data_Format_Error {
            get {
                return ResourceManager.GetString("Data_Format_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data of entity {0} for attribute(s) {1} was not found. For transaction with {2}.
        /// </summary>
        public static string Data_NotFound {
            get {
                return ResourceManager.GetString("Data_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with {0} and {1} could not be uploaded. Error Message: {2}.
        /// </summary>
        public static string Document_Upload_Failed {
            get {
                return ResourceManager.GetString("Document_Upload_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate_IPAddress.
        /// </summary>
        public static string Duplicate_IPAddress {
            get {
                return ResourceManager.GetString("Duplicate_IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate_RobotName.
        /// </summary>
        public static string Duplicate_RobotName {
            get {
                return ResourceManager.GetString("Duplicate_RobotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaskType Name already exists. Please provide another name..
        /// </summary>
        public static string Duplicate_TaskType_Name {
            get {
                return ResourceManager.GetString("Duplicate_TaskType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Exception Handling is failed in the {0} method of {1} class..
        /// </summary>
        public static string Exception_Failed {
            get {
                return ResourceManager.GetString("Exception_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Id of the provided robot is not available..
        /// </summary>
        public static string InCorrectCompanyId {
            get {
                return ResourceManager.GetString("InCorrectCompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip Address of the provided robot is not available ..
        /// </summary>
        public static string InCorrectIpAddress {
            get {
                return ResourceManager.GetString("InCorrectIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value: {0} for property {1} is using reserved keyword(s) which is not permitted. Please modify the name using valid alphanumeric characters only and re-submit..
        /// </summary>
        public static string InvalidCharacter_Validation {
            get {
                return ResourceManager.GetString("InvalidCharacter_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error in job allocation process..
        /// </summary>
        public static string JobAllocationError {
            get {
                return ResourceManager.GetString("JobAllocationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating ATR XML Configuration. Please verify job configuration..
        /// </summary>
        public static string JobConfiguration_ATRCreation_Failed {
            get {
                return ResourceManager.GetString("JobConfiguration_ATRCreation_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job is not found..
        /// </summary>
        public static string JobNotFound {
            get {
                return ResourceManager.GetString("JobNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter values passed to method is Invalid or Empty..
        /// </summary>
        public static string Method_Input_Parameters_Invalid {
            get {
                return ResourceManager.GetString("Method_Input_Parameters_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} method of {1} class returned null for the inputs: {2}.
        /// </summary>
        public static string Method_Returned_Null {
            get {
                return ResourceManager.GetString("Method_Returned_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No task associated with robot..
        /// </summary>
        public static string NoTaskAssociated {
            get {
                return ResourceManager.GetString("NoTaskAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to fetch presentation, as the keys provided do not match with any active records in our database..
        /// </summary>
        public static string PKandRK_Validation_Failed {
            get {
                return ResourceManager.GetString("PKandRK_Validation_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform Instance details not found for platformId {0} and tenantId {1}.
        /// </summary>
        public static string Platform_Data_NotFound {
            get {
                return ResourceManager.GetString("Platform_Data_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} not found in the {1}  table for Parameters: {2}..
        /// </summary>
        public static string RemediatioPlan_NotFound {
            get {
                return ResourceManager.GetString("RemediatioPlan_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request send to the worker for procesing conatins either invalid parameters or some mandatory fields do not contain the required data..
        /// </summary>
        public static string Request_Parameters_Invalid {
            get {
                return ResourceManager.GetString("Request_Parameters_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot Allocation is unsuccessful as robot is not in running state..
        /// </summary>
        public static string RobotAllocationUnsuccessful {
            get {
                return ResourceManager.GetString("RobotAllocationUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Robot instance is already running on this system for this task type. Currently this task has been configured to allow only one instance per system..
        /// </summary>
        public static string RobotInstanceAlreadyRunning {
            get {
                return ResourceManager.GetString("RobotInstanceAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently No Robot is available to pick up this task. Please try after sometime..
        /// </summary>
        public static string RobotNotAvailable {
            get {
                return ResourceManager.GetString("RobotNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script response received null for the actionId: {0} ; ExecutionRequestMessage: {1}..
        /// </summary>
        public static string SEE_Response_Null {
            get {
                return ResourceManager.GetString("SEE_Response_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have faced a error we are unable to resolve at the moment. Please contact the administrator (Support ID: {handlingInstanceId})..
        /// </summary>
        public static string Standard_Error {
            get {
                return ResourceManager.GetString("Standard_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is mismatch between TaskRunMode configured in the client and server side.Please correct the same in the client application..
        /// </summary>
        public static string TaskRunModeMismatch {
            get {
                return ResourceManager.GetString("TaskRunModeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Validation Check Failed..
        /// </summary>
        public static string Validation_Errors {
            get {
                return ResourceManager.GetString("Validation_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Value for the Property {0} is Null or Empty..
        /// </summary>
        public static string Value_NullOrEmpty_Error {
            get {
                return ResourceManager.GetString("Value_NullOrEmpty_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while adding values in the table:  {0}..
        /// </summary>
        public static string ValuesInsertionUnsuccessful {
            get {
                return ResourceManager.GetString("ValuesInsertionUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while updating values in the table : {0}..
        /// </summary>
        public static string ValueUpdationUnsuccessful {
            get {
                return ResourceManager.GetString("ValueUpdationUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while executing view:{0} in the DB. Error Message:{1}.
        /// </summary>
        public static string ViewExecutionUnsuccessful {
            get {
                return ResourceManager.GetString("ViewExecutionUnsuccessful", resourceCulture);
            }
        }
    }
}
