//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infosys.Solutions.Superbot.Infrastructure.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InfoMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InfoMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infosys.Solutions.Superbot.Infrastructure.Common.InfoMessages", typeof(InfoMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_{1}_{2:yyyy-MM-dd_hh-mm-ss-tt}.txt.
        /// </summary>
        public static string Attachment_FileName {
            get {
                return ResourceManager.GetString("Attachment_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Info]: Anomaly Detected for {0} in {1} - {2} .
        /// </summary>
        public static string EMAIL_SUBJECT_ANOMALY_DETECTED {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT_ANOMALY_DETECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Attn] : Environment Scan Anomaly Report for {0} in {1} - {2}.
        /// </summary>
        public static string EMAIL_SUBJECT_ENVIRONMENT_SCAN {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT_ENVIRONMENT_SCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Attn] : Consolidated Environment Scan Anomaly Report for {0} - {1}.
        /// </summary>
        public static string EMAIL_SUBJECT_ENVIRONMENT_SCAN_CONSOLIDATED {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT_ENVIRONMENT_SCAN_CONSOLIDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Attn] : Anomaly Detected for {0} in {1} - {2} .
        /// </summary>
        public static string EMAIL_SUBJECT_NO_REMEDIATION {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT_NO_REMEDIATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Attn] : Remediation failure for {0} in {1} - {2} .
        /// </summary>
        public static string EMAIL_SUBJECT_REMEDIATION_FAILURE {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT_REMEDIATION_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Info] : Remediation Success for {0} in {1} - {2}.
        /// </summary>
        public static string EMAIL_SUBJECT_REMEDIATION_SUCCESS {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT_REMEDIATION_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Attn] : Remediation Success for {0} in {1} - {2}.
        /// </summary>
        public static string EMAIL_SUBJECT_REMEDIATION_SUCCESS_ATTACHMENT {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT_REMEDIATION_SUCCESS_ATTACHMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Info]: Component Health Overview in {0} - {1}.
        /// </summary>
        public static string EMAIL_SUBJECT_SUMMARY {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Attn] : Notification wait operation timed out for {0} in {1} - {2} .
        /// </summary>
        public static string EMAIL_SUBJECT_THRESHOLD_BREACH {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT_THRESHOLD_BREACH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///				&lt;td&gt;
        ///					&lt;table style=&quot;width:1100px;
        ///					margin-right:50px;
        ///					margin-left:50px;
        ///					font-family: &apos;Open Sans&apos;;
        ///					font-size: 14px;
        ///					color: #333333;
        ///					background-color:#FFFFFF;
        ///					border-collapse: separate;
        ///					border-spacing: 0 10px;&quot;&gt;
        ///					{0}
        ///					&lt;/table&gt;
        ///				&lt;/td&gt;						
        ///			&lt;/tr&gt;.
        /// </summary>
        public static string Final_Body {
            get {
                return ResourceManager.GetString("Final_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///	&lt;td style=&quot;margin-top:35px;margin-bottom:10px;font-weight:bold;&quot;&gt;
        ///		Installed Software
        ///	&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///	&lt;td&gt;
        ///		&lt;table class=&quot;InnerMailContainerTable&quot; style=&quot;width:1104px;								
        ///		font-family: &apos;Open Sans&apos;;
        ///		font-size: 14px;
        ///		color: #333333;
        ///		background-color:#FFFFFF;
        ///		border-collapse: collapse;  
        ///		border:1px;
        ///		border-radius:2px;
        ///		margin-bottom: 40px;&quot; cellspacing=&quot;0&quot;&gt;		
        ///		&lt;tr &gt;
        ///			&lt;th&gt;					
        ///				&lt;table style=&quot;width:1104px;border-collapse: collapse;font-family: &apos;Open Sans&apos;;fo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Installed_Software_Body {
            get {
                return ResourceManager.GetString("Installed_Software_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr &gt;
        ///									&lt;td&gt;					
        ///										&lt;table style=&quot;width:1104px;border-collapse: collapse;font-family: &apos;Open Sans&apos;;font-size: 14px;&quot; cellspacing=&quot;0&quot;&gt;
        ///											&lt;tr&gt;
        ///												&lt;td style=&quot;color: #333333;
        ///													width:11%;height:40px;border-right: 1px solid #DDDDDD;border-bottom: 1px solid #DDDDDD;border-left: 1px solid #DDDDDD;padding-left:5px;&quot;&gt;
        ///													{0}
        ///												&lt;/td&gt;	
        ///												&lt;td style=&quot;color: #333333;
        ///													width:11%;height:40px;border-right: 1px solid #DDDDDD;border- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Installed_Software_Row {
            get {
                return ResourceManager.GetString("Installed_Software_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} method of {1} class executed successfully..
        /// </summary>
        public static string Method_Execution_End {
            get {
                return ResourceManager.GetString("Method_Execution_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing the {0} method of {1} class..
        /// </summary>
        public static string Method_Execution_Start {
            get {
                return ResourceManager.GetString("Method_Execution_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///	&lt;td style=&quot;margin-top:35px;margin-bottom:10px;font-weight:bold;&quot;&gt;
        ///		OS Details
        ///	&lt;/td&gt;				
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///	&lt;td&gt;
        ///		&lt;table class=&quot;InnerMailContainerTable&quot; style=&quot;width:1104px;								
        ///		font-family: &apos;Open Sans&apos;;
        ///		font-size: 14px;
        ///		color: #333333;
        ///		background-color:#FFFFFF;
        ///		border-collapse: collapse;  
        ///		border:1px;
        ///		border-radius:2px;
        ///		margin-bottom: 40px;&quot; cellspacing=&quot;0&quot;&gt;		
        ///		&lt;tr &gt;
        ///			&lt;th&gt;					
        ///				&lt;table style=&quot;width:1104px;border-collapse: collapse;font-family: &apos;Open Sans&apos;;font-s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OSDetails_Body {
            get {
                return ResourceManager.GetString("OSDetails_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr &gt;
        ///									&lt;td&gt;					
        ///										&lt;table style=&quot;width:1104px;border-collapse: collapse;font-family: &apos;Open Sans&apos;;font-size: 14px;&quot; cellspacing=&quot;0&quot;&gt;
        ///											&lt;tr&gt;
        ///												&lt;td style=&quot;color: #333333;
        ///													width:11%;height:40px;border-right: 1px solid #DDDDDD;border-bottom: 1px solid #DDDDDD;border-left: 1px solid #DDDDDD;padding-left:5px;&quot;&gt;
        ///													{0}
        ///												&lt;/td&gt;	
        ///												&lt;td style=&quot;color: #333333;
        ///													width:11%;height:40px;border-right: 1px solid #DDDDDD;border- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OSDetails_Row {
            get {
                return ResourceManager.GetString("OSDetails_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///	&lt;td style=&quot;margin-top:35px;margin-bottom:10px;font-weight:bold;&quot;&gt;
        ///		Screen Resolution
        ///	&lt;/td&gt;				
        ///&lt;/tr&gt;			
        ///&lt;tr&gt;
        ///	&lt;td&gt;
        ///		&lt;table class=&quot;InnerMailContainerTable&quot; style=&quot;width:1104px;								
        ///		font-family: &apos;Open Sans&apos;;
        ///		font-size: 14px;
        ///		color: #333333;
        ///		background-color:#FFFFFF;
        ///		border-collapse: collapse;  
        ///		border:1px;
        ///		border-radius:2px;
        ///		margin-bottom: 20px;&quot; cellspacing=&quot;0&quot;&gt;		
        ///		&lt;tr &gt;
        ///			&lt;th&gt;					
        ///				&lt;table style=&quot;width:1104px;border-collapse: collapse;font-family: &apos;Open Sa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SR_Body {
            get {
                return ResourceManager.GetString("SR_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///									&lt;td&gt;
        ///										&lt;table style=&quot;width:1104px;border-collapse: collapse;font-family: &apos;Open Sans&apos;;font-size: 14px;&quot; cellspacing=&quot;0&quot;&gt;
        ///												&lt;tr&gt;
        ///													&lt;td style=&quot;color: #333333;
        ///														width:20%;height:40px;border-right: 1px solid #DDDDDD;border-bottom: 1px solid #DDDDDD;border-left: 1px solid #DDDDDD;padding-left:5px;&quot;&gt;
        ///														{0}
        ///													&lt;/td&gt;									
        ///													&lt;td style=&quot;color: #333333;
        ///														width:20%;height:40px;border-right: 1px solid #DDDDD [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SR_Row {
            get {
                return ResourceManager.GetString("SR_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///	&lt;td&gt;
        ///		&lt;table class=&quot;InnerMailContainerTable&quot; style=&quot;width:1104px;
        ///		margin-right:50px;
        ///		font-family: &apos;Open Sans&apos;;
        ///		font-size: 14px;
        ///		color: #333333;
        ///		background-color:#FFFFFF;
        ///		border-collapse: collapse;  
        ///		border:1px;
        ///		border-radius:2px;
        ///		margin-bottom: 40px;&quot; cellspacing=&quot;0&quot;&gt;					
        ///		&lt;tr &gt;
        ///			&lt;td&gt;					
        ///				&lt;table style=&quot;width:1104px;border-collapse: collapse;font-family: &apos;Open Sans&apos;;font-size: 14px;&quot; cellspacing=&quot;0&quot;&gt;
        ///					&lt;tr&gt;
        ///						&lt;th style=&quot;color: #333333;
        ///							width:20 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SummaryNotiffication_Body {
            get {
                return ResourceManager.GetString("SummaryNotiffication_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///	&lt;td&gt;
        ///		&lt;table style=&quot;width:1104px;border-collapse: collapse;font-family: &apos;Open Sans&apos;;font-size: 14px;&quot; cellspacing=&quot;0&quot;&gt;
        ///				&lt;tr&gt;
        ///					&lt;td style=&quot;color: #333333;
        ///						width:20%;height:40px;border-right: 1px solid #DDDDDD;border-bottom: 1px solid #DDDDDD;border-left: 1px solid #DDDDDD;padding-left:5px;&quot;&gt;
        ///						{0}
        ///					&lt;/td&gt;									
        ///					&lt;td style=&quot;color: #333333;
        ///						width:20%;height:40px;border-right: 1px solid #DDDDDD;border-bottom: 1px solid #DDDDDD;padding-left:5px;&quot;&gt;
        ///						{1}
        ///					 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SummaryNotification_Row {
            get {
                return ResourceManager.GetString("SummaryNotification_Row", resourceCulture);
            }
        }
    }
}
