//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infosys.Solutions.ConfigurationManager.Resource.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Environment_Scan_Metric
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Environment_Scan_Metric()
        {
            this.Environment_Scan_Metric_Details = new HashSet<Environment_Scan_Metric_Details>();
        }
    
        public int EnvironmentScanMetricID { get; set; }
        public Nullable<int> Version { get; set; }
        public string ResourceID { get; set; }
        public int ObservableID { get; set; }
        public int TenantID { get; set; }
        public int PlatformID { get; set; }
        public System.DateTime GeneratedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Environment_Scan_Metric_Details> Environment_Scan_Metric_Details { get; set; }
    }
}
