//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infosys.Solutions.ConfigurationManager.Resource.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class errors
    {
        public int id { get; set; }
        public string systemname { get; set; }
        public string parametername { get; set; }
        public string errorcode { get; set; }
        public string errordesc { get; set; }
        public System.DateTime createdate { get; set; }
    }
}
