//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infosys.Solutions.ConfigurationManager.Resource.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class observable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public observable()
        {
            this.observable_resource_map = new HashSet<observable_resource_map>();
            this.resourcetype_observable_action_map = new HashSet<resourcetype_observable_action_map>();
            this.resourcetype_observable_remediation_plan_map = new HashSet<resourcetype_observable_remediation_plan_map>();
            this.resource_observable_remediation_plan_map = new HashSet<resource_observable_remediation_plan_map>();
            this.resourcetype_observable_action_map1 = new HashSet<resourcetype_observable_action_map>();
            this.resource_observable_action_map = new HashSet<resource_observable_action_map>();
            this.Audit_Logs = new HashSet<Audit_Logs>();
            this.resourcetype_observable_map = new HashSet<resourcetype_observable_map>();
        }
    
        public int ObservableId { get; set; }
        public string ObservableName { get; set; }
        public string UnitOfMeasure { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public System.DateTime ValidityStart { get; set; }
        public System.DateTime ValidityEnd { get; set; }
        public int TenantId { get; set; }
        public string DataType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<observable_resource_map> observable_resource_map { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<resourcetype_observable_action_map> resourcetype_observable_action_map { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<resourcetype_observable_remediation_plan_map> resourcetype_observable_remediation_plan_map { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<resource_observable_remediation_plan_map> resource_observable_remediation_plan_map { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<resourcetype_observable_action_map> resourcetype_observable_action_map1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<resource_observable_action_map> resource_observable_action_map { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Audit_Logs> Audit_Logs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<resourcetype_observable_map> resourcetype_observable_map { get; set; }
    }
}
