//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infosys.Solutions.ConfigurationManager.Resource.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class portfolio_project_map
    {
        public int portfolioprjmapid { get; set; }
        public string portfolioid { get; set; }
        public Nullable<int> projectid { get; set; }
        public string createdby { get; set; }
        public System.DateTime createdate { get; set; }
        public string modifiedby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public Nullable<byte> isdeleted { get; set; }
    }
}
