//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infosys.Solutions.ConfigurationManager.Resource.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipient_configuration
    {
        public int RecipientConfigId { get; set; }
        public string ResourceId { get; set; }
        public string ReferenceType { get; set; }
        public string RecipientName { get; set; }
        public string ReferenceKey { get; set; }
        public string ReferenceValue { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int TenantId { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
