//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infosys.Solutions.ConfigurationManager.Resource.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class resourcetype
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public resourcetype()
        {
            this.resourcetype_observable_action_map = new HashSet<resourcetype_observable_action_map>();
            this.resourcetype_observable_remediation_plan_map = new HashSet<resourcetype_observable_remediation_plan_map>();
            this.resourcetype_metadata = new HashSet<resourcetype_metadata>();
            this.resourcetype_observable_map = new HashSet<resourcetype_observable_map>();
        }
    
        public int ResourceTypeId { get; set; }
        public string ResourceTypeName { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public System.DateTime ValidityStart { get; set; }
        public System.DateTime ValidityEnd { get; set; }
        public int TenantId { get; set; }
        public Nullable<bool> IsMainEntiry { get; set; }
        public string Type { get; set; }
        public string PlatfromType { get; set; }
        public string ResourceTypeDisplayName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<resourcetype_observable_action_map> resourcetype_observable_action_map { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<resourcetype_observable_remediation_plan_map> resourcetype_observable_remediation_plan_map { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<resourcetype_metadata> resourcetype_metadata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<resourcetype_observable_map> resourcetype_observable_map { get; set; }
    }
}
